export const PERMISSIONS = {
  USER_READ: "users:read",
  USER_CREATE: "users:create",
  USER_UPDATE: "users:update",
  USER_DISABLE: "users:disable",
  CONTACT_READ: "contacts:read",
  CONTACT_CREATE: "contacts:create",
  CONTACT_UPDATE: "contacts:update",
  CONTACT_DELETE: "contacts:delete",
  COMPANY_READ: "companies:read",
  COMPANY_CREATE: "companies:create",
  COMPANY_UPDATE: "companies:update",
  COMPANY_DELETE: "companies:delete",
  PRODUCT_READ: "products:read",
  PRODUCT_CREATE: "products:create",
  PRODUCT_UPDATE: "products:update",
  PRODUCT_DELETE: "products:delete",
  ORDER_READ: "orders:read",
  ORDER_CREATE: "orders:create",
  ORDER_UPDATE: "orders:update",
  DEAL_READ: "deals:read",
  DEAL_CREATE: "deals:create",
  DEAL_UPDATE: "deals:update",
  DEAL_DELETE: "deals:delete",
  ACTIVITY_READ: "activities:read",
  ACTIVITY_CREATE: "activities:create",
  DASHBOARD_READ: "dashboard:read",
  REMINDER_READ: "reminders:read",
  REMINDER_CREATE: "reminders:create",
  CSV_IMPORT: "csv:import",
  CSV_EXPORT: "csv:export",
  AUDIT_READ: "audit:read"
  ,
  CONVERSATIONS_READ: "conversations:read",
  CONVERSATIONS_SEND: "conversations:send",
  DEAL_COMMENTS_READ: "deal-comments:read",
  DEAL_COMMENTS_CREATE: "deal-comments:create"
};

const matrix = {
  owner: ["*"],
  admin: [
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE, PERMISSIONS.USER_DISABLE,
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_CREATE, PERMISSIONS.CONTACT_UPDATE, PERMISSIONS.CONTACT_DELETE,
    PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_CREATE, PERMISSIONS.COMPANY_UPDATE, PERMISSIONS.COMPANY_DELETE,
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_UPDATE, PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.ORDER_READ, PERMISSIONS.ORDER_CREATE, PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.DEAL_READ, PERMISSIONS.DEAL_CREATE, PERMISSIONS.DEAL_UPDATE, PERMISSIONS.DEAL_DELETE,
    PERMISSIONS.ACTIVITY_READ, PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_READ,
    PERMISSIONS.CSV_IMPORT, PERMISSIONS.CSV_EXPORT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_SEND,
    PERMISSIONS.DEAL_COMMENTS_READ, PERMISSIONS.DEAL_COMMENTS_CREATE
  ],
  sales: [
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_CREATE, PERMISSIONS.CONTACT_UPDATE,
    PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_CREATE, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.ORDER_READ, PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.DEAL_READ, PERMISSIONS.DEAL_CREATE, PERMISSIONS.DEAL_UPDATE,
    PERMISSIONS.ACTIVITY_READ, PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_READ,
    PERMISSIONS.CSV_IMPORT, PERMISSIONS.CSV_EXPORT,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_SEND,
    PERMISSIONS.DEAL_COMMENTS_READ, PERMISSIONS.DEAL_COMMENTS_CREATE
  ],
  staff: [
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_CREATE, PERMISSIONS.CONTACT_UPDATE,
    PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_CREATE, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.ORDER_READ, PERMISSIONS.ORDER_CREATE, PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.DEAL_READ, PERMISSIONS.DEAL_CREATE, PERMISSIONS.DEAL_UPDATE,
    PERMISSIONS.ACTIVITY_READ, PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_READ,
    PERMISSIONS.CSV_IMPORT, PERMISSIONS.CSV_EXPORT,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_SEND,
    PERMISSIONS.DEAL_COMMENTS_READ, PERMISSIONS.DEAL_COMMENTS_CREATE
  ],
  user: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ, PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_SEND,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.DEAL_CREATE, PERMISSIONS.DEAL_READ,
    PERMISSIONS.CONTACT_CREATE
  ]
};

const allKnownPermissions = new Set(Object.values(PERMISSIONS));

export function requirePermission(permission) {
  return (req, res, next) => {
    if (!allKnownPermissions.has(permission)) {
      return res.status(500).json({ message: `Unknown permission: ${permission}` });
    }
    const role = req.user?.role;
    const allowed = matrix[role] || [];
    if (allowed.includes("*") || allowed.includes(permission)) {
      return next();
    }
    return res.status(403).json({ message: "Forbidden" });
  };
}
